# Generated by Django 5.2.4 on 2026-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Classifier", "0005_alter_cropprediction_id_alter_prediction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cropprediction",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cropprediction",
            name="location_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cropprediction",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
